# run: conda env create --file environment.yml
name: test-env
dependencies:
- python>=3.5
- anaconda
- pip
- pip:
  # works for regular pip packages
  - docx
  - gooey
  - matplotlib~=3.5.2  # pin version for pip
  - pandas~=0.24.2
  - numpy~=1.21.6  # pin version for conda
  - requests_cache
  - sphinx
  - pydata_sphinx_theme
  # and for wheels
  - http://www.lfd.uci.edu/~gohlke/pythonlibs/bofhrmxk/opencv_python-3.1.0-cp35-none-win_amd64.whl